### ISSUE TITLE
tslint.json doesn't fully reflect the Style Guide

### ISSUE THREAD

**Issue by kitsonk** [dojo/dojo-package-template#34]
There are inconstancies between the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md) and the `tslint.json`.

**Comment by novemberborn** [comment]
@kitsonk as per <https://github.com/dojo/meta/issues/43> I don't think `tslint` can save us here. We could wait until <https://github.com/eslint/typescript-eslint-parser> matures, or actively try and help that along. Then we get access to the full ESLint ecosystem and we'll be able to bring linting in line with the style guide.
